- name: サービスマネージャー( initd or systemd )の取得
  block:
  - name: ファクト収集
    setup:
      filter: "ansible_service_mgr"
  - name: 'サービスマネージー名を出力'
    set_fact:
      service_mgr: "{{ ansible_service_mgr }}"
  - name: 結果の表示
    debug:
      var: service_mgr

- name: 時刻同期のデーモンをインストール、設定
  block:
  - block:
    - name: systemdの場合はsystemd-timesyncdを利用する
      copy:
        src: files/timesyncd.conf.d
        dest: /etc/systemd/
    - name: デフォルトの設定ファイルを削除
      file:
        path: /etc/systemd/timesyncd.conf
        state: absent
    when: service_mgr == "systemd"
  - block:
    - name: OpenRCの場合はntpdを利用する
      portage: >
        package="net-misc/ntp"
        sync=no
        deep=no
        state=present
    - name: ntpd起動
      service: >-
        name=ntpd
        state=started
        enabled=yes
    when: service_mgr == "initd"
