- name: nerdctlセットアップ
  vars:
    package_list:
    - sys-cluster/kubectl
    - app-containers/nerdctl
    - sys-apps/rootlesskit
    - app-containers/slirp4netns
  block:
  - name: kubectl、nerdctl関連パッケージ、package.accept_keywords配下にファイルを置く
    loop: "{{ package_list }}"
    lineinfile:
      path: "/etc/portage/package.accept_keywords/{{ item | regex_replace('^.*\\/(.*)$', '\\1') }}"
      line: "{{ item }} **"
      # regexp には ** のような正規表現は使えなかった。pythonのエラーになる。
      # またバックスラッシュでのエスケープもエラーになる。
      regexp: "^{{ item }} .*$"
      state: present
      create: yes
  - name: nerdctl関連、インストール
    loop: "{{ package_list }}"
    portage: >-
      package={{ item }}
      state=present

- name: k3sをインストール
  block:
  - name: ロールの確認
    debug:
      msg: "{{ k3s_role }}"
  - name: サービスレベル、デプロイ環境の確認
    debug:
      msg: "{{ service_level }}"
  - name: カーネルコマンドラインを修正
    replace:
      dest: '/boot/cmdline.txt'
      regexp: 'rootdelay=10 init=/sbin/init'
      replace: 'rootdelay=10 cgroup_memory=1 cgroup_enable=memory init=/sbin/init'
    register: cmdline
  - name: 再起動
    when: cmdline.changed == true
    reboot:
  - name: k3sがインストールされているかチェック
    shell: "which k3s"
    register: k3s_check
    failed_when: k3s_check.rc not in [0,1]
  - name: kubectl_checkの確認
    debug:
      msg: "{{ k3s_check }}"
  - name: k3sサーバをインストール
    when: k3s_role == 'server' and k3s_check.rc == 1
    shell: |-
      curl -sfL https://get.k3s.io | sh -s - --disable-agent --write-kubeconfig-mode 644
  - name: k3sエージェントをインストール
    block:
      - name: サーバのキーを取得
        shell: |-
          cat /var/lib/rancher/k3s/server/node-token
        delegate_to: k3s-{{ service_level }}-server
        register: server_token
      - name: k3sサーバのIPアドレスの取得
        shell: |-
          ip addr show end0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1
        delegate_to: k3s-{{ service_level }}-server
        register: server_ip
      - name: k3sサーバのIPアドレスの表示
        debug:
          msg: "{{ server_ip }}"
      - name: k3sのエージェントのインストール
        shell: |-
          curl -sfL https://get.k3s.io | K3S_TOKEN={{ server_token.stdout }} K3S_URL=https://{{ server_ip.stdout }}:6443 sh - # K3S_URLはhostsに記載してあってもIPアドレスである必要があった。
    when: k3s_role == 'agent' and k3s_check.rc == 1
