---
- name: softether
  gather_facts: true
  become: yes # https://qiita.com/imoyoukan/items/12832aecd956d14b03f5 https://docs.ansible.com/ansible/2.9_ja/user_guide/become.html
  hosts: softether
  roles:
    - common/user_add
    - sdcard
    - softether
    # - common/utility_install
