# build.shで作成したイメージのmake.confのmergeのオプションにdeepがついており非常に時間がかかるので外す
# EMERGE_DEFAULT_OPTS="--jobs --newrepo --newuse --changed-use --changed-deps --changed-slot --deep --tree --unordered-display --nospinner --backtrack=3000 --complete-graph --with-bdeps=y --rebuild-if-new-rev --rebuild-if-new-ver --rebuild-if-unbuilt --rebuilt-binaries --usepkg=y --buildpkg-exclude 'virtual/* sys-kernel/*-sources */*-bin acct-user/* acct-group/*'"

# make.conf について
# default opts 
# https://wiki.gentoo.org/wiki/EMERGE_DEFAULT_OPTS/ja
- name: make.conf を修正
  block:
  - name: make.conf に PYTHON_TARGETS を追加
    lineinfile:
      path: '/etc/portage/make.conf'
      regexp: '^PYTHON_TARGETS='
      line: 'PYTHON_TARGETS="python3_10 python3_11 python3_12"'
      state: present
  - name: CPUのコア数を取得
    shell: 'cat /proc/cpuinfo | grep processor | wc -l'
    register: cpu_num
    check_mode: no
    changed_when: false
  - name: CPU数を表示
    debug:
      msg: "{{ cpu_num.stdout }}"
  - name: make.conf EMERGE_DEFAULT_OPTS を変更する
    lineinfile:
      path: '/etc/portage/make.conf'
      regexp: '^EMERGE_DEFAULT_OPTS='
      line: "EMERGE_DEFAULT_OPTS=\"--usepkg=y --jobs 2 --load-average {{cpu_num.stdout}}\""
  - name: make.conf FEATURES を変更する
    lineinfile:
      path: '/etc/portage/make.conf'
      regexp: '^FEATURES='
      line: "FEATURES=\"buildpkg getbinpkg binpkg-multi-instance clean-logs compress-build-logs parallel-fetch parallel-install -distcc -userpriv -usersandbox -network-sandbox -pid-sandbox \""
      state: present
  - name: portageのビルドをローカルストレージの /usr/local/tmp/portage で行う
    # /var/tmp/portage がzramでマウントされている。
    # 通常、こちらの方が高速だが、大きめのビルドを行う場合、ディスクフルでビルドできないため
    # ローカルドライブに
    # /usr/local/tmp/portage
    # を作成して /etc/portage/make.confの環境変数を変えて、こちらでビルドする。
    # システム系のものはzramでも大丈夫だが、ユーティリティ系のものは大きいものがあるので、
    # このタイミングで切り替える。
    block:
    - name: ディレクトリ作成
      file:
        path: /usr/local/tmp/portage
        state: directory
    - name: ビルド作業用ディレクトリの変更
      # https://wiki.gentoo.org/wiki/Handbook:AMD64/Full/Portage/ja
      lineinfile:
        path: '/etc/portage/make.conf'
        regexp: '^PORTAGE_TMPDIR'
        line: 'PORTAGE_TMPDIR="/usr/local/tmp/portage"'
        state: present
