# portageでの書き方
# https://docs.ansible.com/ansible/2.3/portage_module.html

- name: ディスク書き込みを遅延する処理が入っているか確認
  block:
  - name: 設定ファイルがあるか確認
    stat:
      path: /etc/sysctl.d/99-disk.conf
    register: disk_check
    check_mode: no
    changed_when: false
  - name: 書き込み遅延する設定を追加
    shell: |
      echo -e 'vm.dirty_background_ratio=70\nvm.dirty_ratio=70\nvm.dirty_writeback_centisecs=5000\nvm.dirty_expire_centisecs=30000' >> /etc/sysctl.d/99-disk.conf
    when: not disk_check.stat.exists

- name: ロケール設定
  block:
  - name: タイムゾーン
    timezone:
      name: "Asia/Tokyo"
  - name: システムロケールの確認
    command: cat /etc/locale.gen
    register: localectl_result
    check_mode: no
    changed_when: false
  - name: システムロケールに ja_JP.UTF-8 を追加
    block:
      - name: add locale
        shell: |
          echo 'ja_JP.UTF-8 UTF-8' >> /etc/locale.gen
          locale-gen
          locale_num=$(eselect locale list | grep ja_JP.utf8 | awk '{print $1}' | sed -e 's/\[//' -e 's/\]//')
          eselect locale set $locale_num && . /etc/profile
          echo -e 'LINGUAS="ja"\nL10N="ja"' >> /etc/portage/make.conf
          env-update
        when: localectl_result.stdout.find('ja_JP.UTF-8') == -1

- name: emerge sync
  block:
    - name: sync
      command: |
        emerge --sync

